#! python3
# /Users/jeremientakpe/TwitterSpotBot/data.py

subs = ['Tout a une fin, sauf la banane qui en a deux.\n',
 "Que celui qui n'a pas traversé ne se moque pas de celui qui s'est noyé.\n",
 "L'eau chaude n'oublie pas qu'elle a été froide.\n",
 "On a beau dissimuler ses excréments au fond de l'eau, ils remontent toujours a la surface.\n",
 'Quiconque taquine un nid de guêpe doit savoir courir.\n',
 "Si un animal vous dit qu'il peut parler, il ment probablement.\n",
 'Traverse la rivière avant de te moquer du crocodile.\n',
 'Si en te baignant tu as échappé au crocodile, prends garde au Léopard sur la berge.\n',
 "Si le crocodile a un pantalon, c'est qu'il a enfin trouvé ou ranger sa queue.\n",
 'Qui gobe une noix de coco fait confiance à son anus.\n',
 'L’eau chaude n’oublie pas qu’elle a été froide.\n',
 'On a beau dissimuler ses excréments au fond de l’eau, ils remontent toujours à la surface.\n',
 'Quiconque taquine un nid de guêpe doit savoir courir.\n',
 'Si un animal vous dit qu’il peut parler, il ment probablement.\n',
 'Si en te baignant tu as échappé au crocodile, prends garde au Léopard sur la berge.\n',
 'Un homme qui se noie s’agrippe à l’eau.\n',
 'La reconnaissance d’un âne est un coup de pied.\n',
 'Qui dit bonjour madame, dit au revoir l’argent.\n',
 'Quand les éléphants se battent c’est toujours l’herbe qui est écrasée…\n',
 'Quelle que soit la maigreur d’un éléphant, ses couilles remplissent une marmite.\n',
 'Rire de l’anus de son voisin n’est pas un crime, mais convier toute sa famille pour le faire est inadmissible.\n',
 'Un grain de maïs a toujours tort devant une poule.\n',
 'Le café aura beau se vanter d’être noir, le lait le fera toujours déchanter.\n',
 'Le putois ne sent pas l’odeur de ses aisselles.\n',
 'Si quelqu’un fait semblant de mourir, il faut faire semblant de l’enterrer.\n',
 'L’éléphant ne peut courir et se gratter les fesses en même temps.\n',
 'Quelle que soit la longueur du jet de l’urine, les dernières gouttes retombent toujours entre les cuisses.\n',
 'Qui crache en l’air doit s’attendre à recevoir des crachats sur le visage.\n',
 'On ne marche pas deux fois sur les testicules d’un aveugle.\n',
 "On ne trouve son véritable chemin qu'en cherchant et, souvent, en cherchant seul.\n",
 "On n'est pas orphelin d'avoir perdu père et mère, mais d'avoir perdu l'espoir.\n",
 'Celui qui assiste à une bagarre sans intervenir y prend part.\n',
 'On méprise le termite, mais il peut percer le tronc du baobab.\n',
 'Donne des yeux à un aveugle, il te demandera les sourcils.\n',
 "Le champ du fourbe est grand, mais il n'y pousse guère de mil.\n",
 "Le borgne n'a qu'un œil, mais il pleure quand même.\n",
 'On ne dit pas à une poule : veille sur mon grain de maïs.\n',
 'En visite chez autrui, ouvre les yeux, pas la bouche.\n',
 'Qui osera dire au lion : Ta bouche sent mauvais ?\n']

chin = ["Il vaut mieux se disputer avec quelqu'un d'intelligent que parler à un imbécile.\n",
 'Quand on achète une maison, on regarde les poutres ; quand on prend une femme, il faut regarder la mère.\n',
 "Mieux vaut mille refus qu'une promesse non tenue.\n",
 "Les grandes âmes ont de la volonté, les faibles n'ont que des souhaits.\n",
 "Point n'est besoin d'élever la voix quand on a raison.\n",
 "Un bon chef de famille, c'est celui qui se montre un peu sourd.\n",
 "Ce n'est qu'avec les yeux des autres que l'on peut bien voir ses défauts.\n",
 'Sourire trois fois tous les jours rend inutile tout médicament.\n',
 "En buvant l'eau du puits, n'oubliez pas ceux qui l'ont creusé.\n",
 'Etre homme est facile, être un homme est difficile.\n',
 "Quand le sage désigne la lune, l'idiot regarde le doigt.\n",
 'Aimez votre voisin mais ne supprimez pas votre clôture. \n',
 "Avec de la volonté, on peut accéder au mandarinat, Avec l'audace, on peut devenir riche. \n"]

fran = ['L’absence est l’ennemie de l’amour.\n',
 'Un mauvais accommodement vaut mieux qu’un bon procès.\n',
 'A sot auteur sot admirateur.\n',
 'Tout est géant dans la nature, Aux yeux étroits du peuple nain.\n',
 'Il vaut mieux avoir affaire à Dieu qu’à ses saints.\n',
 'D’où vient l’agneau, là retourne la peau.\n',
 'L’aigle n’engendre point la colombe.\n']

kaby = ['Le chacal ne ronge pas la patte de son frère.\n',
 "Qui n'a pas de parents (paternels) jure par ses oncles maternels.\n",
 'Mieux vaut séparation que mauvaise épouse.\n']

arab = ["L'homme est là où il se place.\n",
 'Si parmi deux choix le mensonge est le meilleur, alors les deux sont mauvais.\n',
 "Les hommes sont unanimes à maudire la vie, mais personne n'a envie de la quitter !\n",
 'Le mérite appartient à celui qui commence, même si le suivant fait mieux."\n',
 'Quand tu lances la flèche de la vérité, trempe toujours la pointe dans du miel.\n',
 'Remue le destin, le destin remuera.\n',
 'Ne pas paraître vaut mieux que paraître.\n',
 "La vie d'ici-bas est comme un pont ; tu y entres par un côté et tu en sors par l'autre.\n",
 'Pour être un bon menteur il faut une bonne mémoire.\n',
 "Quand un chien vous aide à passer le fleuve, vous ne demandez pas s'il a la gale.\n",
 "L'homme intelligent n'est pas celui qui sait reconnaître le bien du mal, mais celui qui sait quel est le moindre mal.\n",
 "L'abeille ne tire pas son miel d'une seule plante.\n",
 "L'homme est à l'image de ses actes ; la cruche ne verse que ce qu'elle contient.\n",
 "Si les yeux voient les étoiles petites, c'est de la faute des yeux, pas des étoiles.\n",
 "Agis avec sincérité : quand tu crois qu'elle peut te nuire, elle te sert.\n",
 'Les promesses de la nuit sont faites de beurre et fondent dès les premiers rayons de soleil.\n',
 'Vise toujours la lune ; si tu la rates, tu tomberas quand même dans les étoiles.\n',
 "L'homme le plus riche est celui qui ose regarder le lendemain.\n",
 "Ne jugez pas le grain de poivre d'après sa petite taille, goûtez-le et vous sentirez comme il pique.\n",
 "L'homme pauvre n'est pas celui dont les mains sont vides, mais celui dont l'âme est vide de désirs.\n",
 'Qui ment pour toi, mentira contre toi.\n']

asie = ['On peut vivre dans une maison exiguë, on ne peut pas vivre avec une âme angoissée.\n',
 "À bout d'endurance, continuer c'est l'endurance.\n",
 'A cause mauvaise, conséquence mauvaise.\n',
 'A celui qui détient le bonheur intérieur, ce sont les quatre saisons qui sont belles. \n',
 'A chaque marmite son couvercle. \n',
 'A court d’argent, adieu le sentiment. \n',
 "À force d'étudier, on parvient aux honneurs. À force de travailler, on parvient à la fortune. \n",
 "A force de couler, l'eau finit par user la pierre. \n",
 'À force de marcher, on finit par atteindre la nuit À force de mentir, on finit par se démentir. \n',
 " À l'arbre droit, l'ombre droite À l'arbre tordu, l'ombre tordu. \n",
 'A la crue, les poissons dévorent les fourmis, à la décrue les fourmis dévorent les poissons. \n',
 "Alors que j'ai envie de me dévouer à mes parents, ils ne sont plus là. \n",
 'Arbre renversé par le vent avait plus de branches que de racines.\n',
 "Au sommet de la montagne où que l'on tourne sa tête la vue est la même. \n",
 "Aucune souffrance n'est telle que la colère, aucun bonheur n'est comparable à la patience. \n",
 'Avant de battre un chien, regarde qui est son maitre. \n',
 "Bavardage est écume sur l'eau, action est goutte d'or. \n",
 'Boeuf rapide cou pelé, femme jolie vite usée. \n',
 'Bonne réputation vaut mieux que beaux habits. \n']

