#! python3
# /Users/jeremientakpe/TwitterSpotBot/data.py

kyw = ['Samir Amin',
 'Ifi Amadiume',
 'Mario de Andrade',
 'Anthony Appiah',
 'Amilcar Cabral',
 'Rocha Chimera',
 'Cheikh Anta Diop',
 'Efua Doorkenoo',
 'J.E. Casely Hayford',
 'Paulin Hountondji',
 'Samuel Johnson',
 'Jomo Kenyatta',
 'Joseph Ki-Zerbo',
 'Antjie Krog',
 'Amina Mama',
 'Mahmood Mamdani',
 'Nelson Mandela',
 'Eugene Marais',
 'Albert Memmi',
 'Eduardo Mondlane',
 'Ezekiel Mphahlele',
 'V.Y. Mudimbe',
 'Kwame Nkrumah',
 'Sol Plaatje',
 'Wole Soyinka',
 'Charles Van Onselen',
 '`Abd al-Rahman Abnudi',
 'Chinua Achebe',
 'Chinua Achebe',
 'Ama Ata Aidoo',
 'Germano Almeida',
 'Ayi Kwei Armah',
 'Amadou Hampâté Bâ',
 'Mariama Bâ',
 'Tahar Ben Jelloun',
 'Mongo Beti',
 'André Brink',
 'Ken Bugul',
 'Syl Cheney-Choker',
 'Driss Chraibi',
 'J.M. Coetzee',
 'Mia Couto',
 'José Craveirinha',
 'Bernard Dadié',
 'Tsitsi Dangarembga',
 'Mohammed Dib',
 'Birago Diop',
 'Boubacar Boris Diop',
 'Assia Djebar',
 'Buchi Emecheta',
 'Daniel O. Fagunwa',
 'Nuruddin Farah',
 'Athol Fugard',
 'Jamal al- Ghitani',
 'Nadine Gordimer',
 'Bessie Head',
 'Bernardo Honwana',
 'Chenjerai Hove',
 'Moses Isegawa',
 'Archibald Campbell Jordan',
 'Elsa Joubert',
 'Cheikh Hamidou Kane',
 'Ungulani Ba Ka Khosa',
 'Ahmadou Kourouma',
 'Camara Laye',
 'Sindiwe Magona',
 'Naguib Mahfouz',
 'Dambudzo Marechera',
 'Thomas Mofolo',
 'Tierno Monenembo',
 'Vusamazulu Credo Mutwa',
 "Ngugi wa Thiong'o",
 'Djibril Tamsir Niane',
 'Sibusiso Nyembezi',
 'Christopher Okigbo',
 'Ben Okri',
 'Ferdinand Oyono',
 "Okot P'Bitek",
 'Nawal El Saadawi',
 'Williams Sassine',
 'Ousmane Sembene',
 'Léopold Sédar Senghor',
 'Mongane Serote',
 'Robert Bin Shabaan',
 'Sony Labou Tansi',
 'Aminata Sow Fall',
 'Wole Soyinka',
 "Tchicaya U Tam'si",
 'Amos Tutuola',
 'Yvonne Vera',
 'José Luandino Vieira',
 'B.W. Vilakazi',
 'Kateb Yacine']

